### ISSUE TITLE
I would like to ask how to modify the key mapping and delete the AIR

### ISSUE THREAD

**Issue by KazunoSatoki** [4yn/brokenithm-kb#1]
I would like to ask how to modify the key mapping and delete the sky key
Hope to get your reply :)

**Comment by 4yn** [comment]
The main way to change key mapping will be to download the source code, modify the keys [here](https://github.com/4yn/brokenithm-kb/blob/dev/src/src/KeyboardSimulator.cpp#L17) and try to compile it yourself, but that is not very easy.

To remove air keys you can hide air keys with css
Open your version of the package and edit the [/res/www/index.html](https://github.com/4yn/brokenithm-kb/blob/358cda7e43883655272d27b44cb71d38b4c3e138/res/www/index.html#L37) file:
```css
.air-container {
  display: none;
}
```

**Comment by KazunoSatoki** [comment]
Thank you very much for your reply. I'm using my Android phone as a virtual button to play this game, so I'm having a lot of trouble.
