### ISSUE TITLE
Missing ws2_32.dll

### ISSUE THREAD

**Issue by D-06** [4yn/brokenithm-kb#3]
![20220226_125029](https://user-images.githubusercontent.com/82329926/155831139-b9e1325d-a4e0-4752-ae3d-2031376d6084.jpg)

**Comment by 4yn** [comment]
Looks like windows 7? I don't think the build supports it. If you are feeling adventurous you can try to compile it on your own machine.

**Comment by 4yn** [comment]
You might need to disable the "URL Generation" code for it to work. I use [this](https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-gethostnamew) to find your machine IP addresses to generate links and it looks like it only works on windows 8 and later.
