### ISSUE TITLE
I'm using my android phone for it, but only the two rightmost sliders work and are not mapped correctly, they are mapped to the two rightmost sliders in the game

### ISSUE THREAD

**Issue by SUPER-CRC** [4yn/brokenithm-kb#5]
I'm using my android phone for it, but only the two rightmost sliders work and are not mapped correctly, they are mapped to the two rightmost sliders in the gameI wonder if it's because I have a keyboard mapped in my "segatools"?（The translation may not be accurate - Chinese）

**Comment by SUPER-CRC** [comment]
It is CHUNITHM Luminous

**Comment by 4yn** [comment]
This is illegal. I will proceed to delete this issue.
